messages:
  announce-catch: -1
  announce-new-1st: -1
  only-announce-fishing-rod: false
  broadcast-start: true
  broadcast-stop: true
  show-top-on-ending: true
  contest-bar-color: 'blue'
  top-number: 3
