
experience:
  # Rewards per stage, wheat, cocoa, beets, carrots
  per-growth-stage: 1.3
  # Rewards per height of cactus, sugar cane, bamboo
  per-pillar-height: 4
  # Rewards when you break a grown melon or pumpkin
  per-block-crop: 24
  # The farming level at which fertilize doesn't grant xp
  fertilize-falloff-level: 20
  # Multiplier applied if you fail to fertilize
  fertilize-failure-multiplier: 0.5
  # How much xp should fertilizing grant?
  base-fertilize-exp: 2

unique-crops:
  quality-to-upgrade-to-unique: 5
  quality-to-unique-chance: 1.0

language:
  quality-prefix-2: "Pretty Good"
  quality-prefix-3: "Kinda Great"
  quality-prefix-4: "Pretty Snazzy"
  quality-prefix-5: "Legendary"

generic-crop-format:
  name: "{quality-color}{quality-prefix}{name}"
  lore:
    - "&fQuality: {quality-color}{quality-stars}"

croptions:
  WHEAT:
    seeds-drop:
      material: WHEAT_SEEDS
      chance: 0.25
      quality-increase-chance: 0.1
      quality-increase-chance-per-level: 0.01
      min-amount: 1
      max-amount: 1
    drop1:
      material: WHEAT
      chance: 1.0
      min-amount: 1
      max-amount: 2
      min-bonus-per-level: 0.01
      max-bonus-per-level: 0.02